### ISSUE TITLE
[REQUEST] Google Chrome Web Store

### ISSUE THREAD

**Issue by Danilka** [harunurhan/google-result-highlighter#2]
You should absolutely release this extension to the chrome store. It does the job well and makes frequent similar searches much easier.
I'll be first in line to install officially!!

**Comment by harunurhan** [comment]
@Danilka It is good to see there are users other than me :) . When I have time I will improve it a little bit and release it.

**Comment by harunurhan** [comment]
Added https://chrome.google.com/webstore/detail/google-result-highlighter/kimgfbhinaigoahlilmenjgbkcdfbeic

**Comment by Danilka** [comment]
WOW! This is the best customer support I'VE EVER SEEN!!!

Got my coworker to use it as well.

THANKS!!
